name: docker ci-cd build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    
    - id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "C046Y9JBJ92"
        payload: |
          {
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
   
    - name: Build the Docker image
      run: docker build -t anirudhvasu/demoapp:$GITHUB_SHA .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push the Docker image
      run: docker push anirudhvasu/demoapp:$GITHUB_SHA
    
    - uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "C046Y9JBJ92"
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}      

    
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch