name: docker ci-cd build

on:
  push:
    branches: [ main ]
env:
  REGISTRY: anirudhvasu
  IMAGE_NAME: demoapp
  SLACK_CHANNEL_MAP: |
    {
      "main":{
        slack: "C046Y9JBJ92"
      }
      "develop":{
        slack: "C046Y9JBJ93"
      }
    }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    
    - id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: ${{fromJson(env.SLACK_CHANNEL_MAP.[steps.extract_branch.outputs.branch].slack)}}
        payload: |
          {
            "attachments": [
              {
                "pretext": "Deployment started: ${{ steps.extract_branch.outputs.branch }}",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
   
    - name: Build the Docker image
      run: docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push the Docker image
      run: docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
    
    - uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: ${{fromJson(env.SLACK_CHANNEL_MAP.[steps.extract_branch.outputs.branch].slack)}}
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "attachments": [
              {
                "pretext": "Deployment finished: ${{ steps.extract_branch.outputs.branch }}",
                "color": "${{ job.status == 'success' && '28a745' || 'e01563' }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ job.status == 'success' && 'Completed' || 'Failed' }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: always()    

    
