name: docker ci-cd build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t anirudhvasu/demoapp:$(date +%s) .

    - name: push the Docker image
      run: docker push anirudh/demoapp:$(date +%s)
    